version: "3.7"
services:

  servicea:
    image: loffek/servicea
    ports:
      - 3000:3000
    environment:
      PORT: 3000

  serviceb:
    image: loffek/serviceb
    ports:
      - 8000:8000
    environment:
      SERVICE_A_URL: servicea
      SERVICE_A_PORT: 3000
      PORT: 8000
    depends_on:
      - servicea

networks:
  default:
    name: dreams
