version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker

      - run:
        name: Pull images
        command: |
          docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
          docker pull $DOCKER_HUB_USER_ID/servicea:latest
          docker pull $DOCKER_HUB_USER_ID/serviceb:latest

      - run:
        name: Run integration tests
        command: |
          make test

