version: 2
jobs:
  build:
    docker:
      - image: docker:1.13.1
    working_directory: ~/repo
    steps:
      - run:
          name: Install Docker Compose
          command: |
            set -xe
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose

      - setup_remote_docker

      - checkout

      - run:
          name: Pull images
          command: |
            docker login -u $DOCKER_HUB_USER_ID -p $DOCKER_HUB_PWD
            docker pull $DOCKER_HUB_USER_ID/servicea:latest
            docker pull $DOCKER_HUB_USER_ID/serviceb:latest

      - run:
          name: Run integration tests
          command: |
            docker-compose up -d
            echo "waiting for cluster to start..."
            docker-compose -f testrunner/docker-compose.testrunner.yml run testrunner yarn test
