version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
        environment:
          SERVICE_B_URI: http://serviceb:8000

      - image: loffek/servicea:latest
        name: servicea
        environment:
          PORT: 3000
        auth:
            username: $DOCKER_HUB_USER_ID
            password: $DOCKER_HUB_PWD

      - image: loffek/serviceb:latest
        name: serviceb
        environment:
          SERVICE_A_URL: servicea
          SERVICE_A_PORT: 3000
          PORT: 8000
        auth:
            username: $DOCKER_HUB_USER_ID
            password: $DOCKER_HUB_PWD

    working_directory: ~/repo/testrunner
    steps:
      - checkout:
          path: ~/repo

      - run:
          name: print dir
          command: |
            pwd
            ls -a .
            ls -a ~

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-

      - run:
          name: Install Dependencies
          command: yarn install

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run integration tests
          command: |
            yarn test
